export const AMBIGUOUS_ADMIN = new Set([
  "new york",
  "washington",
  "oklahoma",
  "kansas",
  "missouri",
  "nebraska",
  "indiana",
  "iowa",
  "texas",
  "georgia",
  "florida",
  "colorado",
  "arizona",
  "utah",
  "nevada",
  "montana",
  "wyoming",
  "delaware",
  "maryland",
  "virginia",
  "california",
  "louisiana",
  "minnesota",
  "mississippi",
  "arkansas",
  "tennessee",
  "alabama",
  "alaska",
  "idaho",
  "maine",
  "vermont",
  "oregon",
  "hawaii",
  "illinois",
  "michigan",
  "ohio",
  "pennsylvania",
  "wisconsin",
  "south carolina",
  "north carolina",
  "south dakota",
  "north dakota",
  "west virginia",
  "new jersey",
  "new mexico",
  "new hampshire",
  "massachusetts",
  "connecticut",
  "rhode island",
  "kentucky"
]);